routes/web.php
<?php

// Route::get('/', function () {
//     return view('site.home.index');
// });

//Site
Route::get('/', 'SitesController@index');

// Buscar anúncios
Route::any('buscar-anuncios', 'SitesController@searchPublicAdvertisements')->name('anuncios.searchPublicAdvertisements');

// Promoções
Route::get('promocoes', 'SitesController@promotion')->name('promocoes.promotion');

// Sobre
Route::get('sobre', 'SitesController@about')->name('sobre.about');

// Contato
Route::get('contato', 'ContactsController@contact')->name('contato.contact');
Route::post('contato', 'ContactsController@store')->name('contato.store');

// Assinar
Route::get('assine', 'SitesController@sign')->name('assine.sign');

Route::prefix('admin')
	->middleware(['auth'])
	->group(function(){

		//acessando advertisements controller
		Route::resource('anuncios', 'AdvertisementsController');

		//acessando promotions controller
		Route::resource('promocoes', 'PromotionsController');

		// any aceita qualquer tipo de requisicao, post, get , put etc...
		Route::any('anuncios-buscar', 'AdvertisementsController@searchAdminAdvertisements')->name('anuncios.searchAdminAdvertisements');
		
		//Advertisements
		Route::post('anuncios/criar', 'AdvertisementsController@store')->name('anuncios.store');
		Route::get('meu-perfil', 'UsersController@profile')->name('profile');
		Route::post('atualizar-perfil', 'UsersController@profileUpdate')->name('profileUpdate');

		//Promotions
		Route::post('promocoes/criar', 'PromotionsController@store')->name('promocoes.store');
		Route::any('promocoes/publicar{id}', 'PromotionsController@publish')->name('promocoes.publish');
		Route::any('promocoes/despublicar{id}', 'PromotionsController@unpublish')->name('promocoes.unpublish');
	});

Auth::routes();

app/Advertisement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\AdvertisementImage;
use App\RecreationArea;
use App\ExtraItem;
use App\SandwichVariation;
use App\MechanicPart;

class Advertisement extends Model
{
    private $totalPages = 5;
    
    protected $fillable = [
        'user_id', 
        'description', 
        'open_time', 
        'close_time', 
        'email',
        'phone', 
        'price', 
        'social_media', 
        'category',
        'room',
        'capacity',
        'diary_price',
        'delivery',
        'holiday',
        'christmas',
        'new_year',
        'owner_name'
    ];

    public function searchUserAdvertisements(Array $data, $totalPages){
        
        // resgatando anuncios de acordo com o usuario logado
        $user_advertisements = auth()->user()->advertisements();

        //verifica se esta buscando por descricao ou por email e faz a consulta no banco
        return $user_advertisements->where(function ($query) use ($data){
            if (isset($data['owner_name'])){
                $query->where('owner_name', 'LIKE', '%'.$data['owner_name'].'%');
            }
            if (isset($data['descricao'])){
                $query->where('description', 'LIKE', '%'.$data['descricao'].'%');
            }
            if (isset($data['email'])){
                $query->where('email', 'LIKE', '%'.$data['email'].'%');
            }
            if (isset($data['category'])){
                $query->where('category', $data['category']);
            }
        })->paginate($totalPages);
        // outra forma de resgatar de acordo com usuario logado
        //->where('user_id', auth()->user()->id);

        //para debugar a consulta
        //->toSql(); 
    }

    public function searchAdvertisements(Array $data, $totalPages){
        
        //verifica se esta buscando por descricao ou por email e faz a consulta no banco
        return $this->where(function ($query) use ($data){
            if (isset($data['descricao'])){
                $query->where('description', 'LIKE', '%'.$data['descricao'].'%');
            }
            if (isset($data['email'])){
                $query->where('email', 'LIKE', '%'.$data['email'].'%');
            }
            if (isset($data['category'])){
                $query->where('category', $data['category']);
            }
        })->paginate($totalPages);
    }

    public function category($category = null){

        $categories = [
            'CHA' => 'Chácaras',
            'LAN' => 'Lanchonetes',
            'MEC' => 'Mecânicas',
            'SUP' => 'Supermercados',
        ];

        if(!$category){
            return $categories;
        }else{
            return $categories[$category];
        }
    }

    public function recreation_area($recreation_area = null){

        $recreation_areas = [
            'PISCINA' => 'Piscina',
            'CAMPO DE FUTEBOL' => 'Campo de Futebol',
            'QUADRA' => 'Quadra',
            'QUIOSQUE' => 'Quiosque',
        ];

        if(!$recreation_area){
            return $recreation_areas;
        }else{
            return $recreation_areas[$recreation_area];
        }
    }

    public function extra_item($extra_item = null){

        $extra_items = [
            'SINUCA' => 'Sinuca',
            'PEBOLIM' => 'Pebolim',
            'PING PONG' => 'Ping Pong',
        ];

        if(!$extra_item){
            return $extra_items;
        }else{
            return $extra_items[$extra_item];
        }
    }

    public function sandwich_variation($sandwich_variation = null){

        $sandwich_variations = [
            'VEGETARIANO' => 'Vegetariano',
            'VEGANO' => 'Vegano',
            'CACHORRO QUENTE' => 'Cachorro Quente',
            'HAMBURGUER' => 'Hamburguer',
            'PIZZA' => 'Pizza',
            'PANQUECA' => 'Panqueca',
            'ESFIHA' => 'Esfiha',
            'PORÇÕES' => 'Porções',
            'REFRIGERANTES' => 'Refrigerantes',
            'AÇAÍ' => 'Açaí',
        ];

        if(!$sandwich_variation){
            return $sandwich_variations;
        }else{
            return $sandwich_variations[$sandwich_variation];
        }
    }

    public function mechanic_part($mechanic_part = null){

        $mechanic_parts = [
            'ESCAPAMENTOS' => 'Escapamentos',
            'ELÉTRICA' => 'Elétrica',
            'FREIO' => 'Freio',
            'TROCA DE ÓLEO' => 'Troca de óleo',
            'PNEUS' => 'Pneus',
            'MOTORES' => 'Motores',
        ];

        if(!$mechanic_part){
            return $mechanic_parts;
        }else{
            return $mechanic_parts[$mechanic_part];
        }
    }

    public function advertisement_images(){
        return $this->hasMany(AdvertisementImage::class);
    }

    public function recreation_areas(){
        return $this->hasMany(RecreationArea::class);
    }

    public function extra_items(){
        return $this->hasMany(ExtraItem::class);
    }

    public function sandwich_variations(){
        return $this->hasMany(SandwichVariation::class);
    }

    public function mechanic_parts(){
        return $this->hasMany(MechanicPart::class);
    }
}

app/Http/Controllers/AdvertisementsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Advertisement;
use App\User;
use App\AdvertisementImage;
use App\RecreationArea;
use App\ExtraItem;
use App\SandwichVariation;
use App\MechanicPart;
use App\Http\Requests\AdvertisementValidationFormRequest;
use App\Http\Requests\AdvertisementUpdateFormRequest;
use Intervention\Image\Facades\Image;
use File;

class AdvertisementsController extends Controller
{
    private $totalPages = 5;

    public function index(Advertisement $advertisement){

        $advertisements = auth()->user()->advertisements()->paginate($this->totalPages);
        $total_advertisements_per_user = auth()->user()->advertisements()->count();

        // tratamento para se nao houverem anuncios ainda criados
        $msg = '';
        if($advertisements->isEmpty()){
            $msg = 'Não há anúncios criados';
        }

        //categorias
        $categories = $advertisement->category();

    	//transformando variavel advertisements e msg em um array
    	return view('admin.advertisements.index', compact('advertisements', 'msg', 'categories', 'total_advertisements_per_user'));
    }

    public function create(Advertisement $advertisement)
    {
        $categories = $advertisement->category();
        $recreation_areas = $advertisement->recreation_area();
        $extra_items = $advertisement->extra_item();
        $sandwich_variations = $advertisement->sandwich_variation();
        $mechanic_parts = $advertisement->mechanic_part();

        return view('admin.advertisements.create', compact('advertisement', 'categories', 'recreation_areas', 'extra_items', 'sandwich_variations', 'mechanic_parts'));
    }

    public function update(AdvertisementUpdateFormRequest $request, $id){

    	// encontra o usuario ou falha
        $advertisement = Advertisement::findOrFail($id);

        // resgatando categoria
        $category = $request->category;
        if($category == null){
            $category = $advertisement->category;
        }

        // formata campo diary_price para que nao de erro no banco de dados, removendo as virgulas
        $diary_price = $request->diary_price;
        $diary_price_formated = floatval(preg_replace('/[^\d.]/', '', $diary_price));

        // formata campo data para que nao de erro no banco de dados, inserindo uma data ficticia
        $open_time = '2018-01-01 '.$request->open_time;
        $close_time = '2018-01-01 '.$request->close_time;

        //resgatando area de lazer existente desse anuncio
        $existent_rec = Advertisement::find($id)->recreation_areas()->get(['recreation_area']);
        $ext_rec = [];

        //resgatando items extras da area de lazer existente desse anuncio
        $existent_extra = Advertisement::find($id)->extra_items()->get(['extra_item']);
        $ext_extra = [];

        //resgatando variacao de sandwich existente desse anuncio
        $existent_sand = Advertisement::find($id)->sandwich_variations()->get(['sandwich_variation']);
        $ext_sand = [];

        //resgatando variacao de mecanica existente desse anuncio
        $existent_mec = Advertisement::find($id)->mechanic_parts()->get(['mechanic_part']);
        $ext_mec = [];

        //resgatando imagem existente desse anuncio
        $existent_img = Advertisement::find($id)->advertisement_images()->get(['image']);
        $ext_img = [];

        if($category == 'CHA'){

            $holiday = "";
            $christmas = "";
            $new_year = "";

            if($request->holiday == null){
                $holiday = 0;
            }else{
                $holiday = 1;
            }
            if($request->christmas == null){
                $christmas = 0;
            }else{
                $christmas = 1;
            }
            if($request->new_year == null){
                $new_year = 0;
            }else{
                $new_year = 1;
            }

            $cha_values = [
                'user_id' => auth()->id(), 
                'description' => $request->description,
                'email' => $request->email,
                'phone' => $request->phone,
                'social_media' => $request->social_media,
                'owner_name' => $request->owner_name,
                'category' => $category,
                'room' => $request->room,
                'capacity' => $request->capacity,
                'diary_price' => $diary_price_formated,
                'holiday' => $holiday,
                'christmas' => $christmas,
                'new_year' => $new_year,
            ];

            //atualiza requisicao
            $advertisement->update($cha_values);
            
            foreach ($existent_rec as $rec) {
                $ext_rec = $rec->recreation;
            }

            if($request->recreation == null){
                $request->recreation = $ext_rec;
                //salvando checkbox's das chacaras
                self::updateAdvtRecreation($request, $advertisement);
                
            }elseif($ext_rec != $request->recreation){
                $advertisement->recreation_areas()->delete([
                    'advertisement_id' => $advertisement->id
                    //'recreation_area' => $request->recreation
                ]);
                //salvando checkbox's das chacaras
                self::updateAdvtRecreation($request, $advertisement);
            }

            foreach ($existent_extra as $extra_item) {
                $ext_extra = $extra_item->extra;
            }

            if($request->extra == null){
                $request->extra = $ext_extra;
                //salvando checkbox's dos items extras das chacaras
                self::updateAdvtExtraItems($request, $advertisement);
                
            }elseif($ext_extra != $request->extra){
                $advertisement->extra_items()->delete([
                    'advertisement_id' => $advertisement->id
                    //'item' => $request->item
                ]);
                //salvando checkbox's dos items extras das chacaras
                self::updateAdvtExtraItems($request, $advertisement);
            }
                  
        }elseif($category == 'LAN'){

            $delivery = "";
            if($request->delivery == null){
                $delivery = 0;
            }else{
                $delivery = 1;
            }

            $lan_values = [
                'user_id' => auth()->id(), 
                'description' => $request->description,
                'open_time' => $open_time,
                'close_time' => $close_time,
                'email' => $request->email,
                'phone' => $request->phone,
                'social_media' => $request->social_media,
                'owner_name' => $request->owner_name,
                'category' => $request->category,
                'delivery' => $delivery,
            ];

            //atualiza requisicao
            $advertisement->update($lan_values);

            foreach ($existent_sand as $sand) {
                $ext_sand = $sand->sandwich;
            }

            if($request->sandwich == null){
                $request->sandwich = $ext_sand;
                //salvando checkbox's das lanchonetes
                self::updateAdvtSandwich($request, $advertisement);

            }elseif($ext_sand != $request->sandwich){
                $advertisement->sandwich_variations()->delete([
                    'advertisement_id' => $advertisement->id
                    //'sandwich_variation' => $request->sandwich
                ]);
                //salvando checkbox's das lanchonetes
                self::updateAdvtSandwich($request, $advertisement);
            }
        }elseif($category == 'MEC'){

            $mec_values = [
                'user_id' => auth()->id(), 
                'description' => $request->description,
                'open_time' => $open_time,
                'close_time' => $close_time,
                'email' => $request->email,
                'phone' => $request->phone,
                'social_media' => $request->social_media,
                'owner_name' => $request->owner_name,
                'category' => $category,
            ];

            //atualiza requisicao
            $advertisement->update($mec_values);

            foreach ($existent_mec as $mec) {
                $ext_mec = $mec->mechanic;
            }

            if($request->mechanic == null){
                $request->mechanic = $ext_mec;
                //salvando checkbox's das mecanicas
                self::updateAdvtMechanic($request, $advertisement);

            }elseif($ext_mec != $request->mechanic){
                $advertisement->mechanic_parts()->delete([
                    'advertisement_id' => $advertisement->id
                    //'mechanic_part' => $request->mechanic
                ]);
                //salvando checkbox's das lanchonetes
                self::updateAdvtMechanic($request, $advertisement);
            }            

        }elseif($category == 'SUP'){
            
            $delivery = "";
            if($request->delivery == null){
                $delivery = 0;
            }else{
                $delivery = 1;
            }

            $sup_values = [
                'user_id' => auth()->id(), 
                'description' => $request->description,
                'open_time' => $open_time,
                'close_time' => $close_time,
                'email' => $request->email,
                'phone' => $request->phone,
                'social_media' => $request->social_media,
                'owner_name' => $request->owner_name,
                'category' => $request->category,
                'delivery' => $delivery,
            ];

            //atualiza requisicao
            $advertisement->update($sup_values);
        }

        foreach ($existent_img as $img) {
            $ext_img = $img->image;
        }

        if($request->image == null){

resources/views/admin/advertisements/create.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Criar Anúncio')

@section('content_header')
    <h3>Criar novo anúncio</h3>
	<a href="{{route('anuncios.index')}}" class="btn btn-default">Voltar</a>
@stop

@section('content')
<div class="alert alert-warning"><b>Atenção! </b>O tamanho máximo para imagens é de 3 MB. Você pode inserir uma ou mais imagens.</div>
@include('admin.includes.alerts')
<!-- o enctype serve para nao falhar no post devido ao array de images -->
<form action="{{route('anuncios.store')}}" method="post" enctype="multipart/form-data">
	@include('admin.advertisements.create_form')
</form>
@stop

resources/views/admin/advertisements/edit.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Editar Anúncio')

@section('content_header')
    <h1>Editar Anúncio</h1>
	<a href="{{route('anuncios.index')}}" class="btn btn-default">Voltar</a><br><br>
	<div class="alert alert-warning"><b>Atenção! </b>O tamanho máximo para imagens é de 3 MB. Você pode inserir uma ou mais imagens.</div>
	@include('admin.includes.alerts')
@stop

@section('content')
<form action="{{route('anuncios.update', $advertisement->id)}}" method="post" enctype="multipart/form-data">
	<!-- necessario passar esse input pois o metodo update da controller Advertisements soh pode acessador por PUT -->
	<input type="hidden" name="_method" value="put">
	<!-- incluindo formulario -->
	@include('admin.advertisements.edit_form')
</form>
@stop

resources/views/admin/advertisements/index.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Anúncios')

@section('content_header')
    <h3>Anúncios</h3>
    @if($total_advertisements_per_user >= 1)
        <a class="btn btn-primary" disabled>Criar novo anúncio</a><br><br>
        <p><b>Você atingiu o número máximo de anúncios.</b></p>
    @else
        <a href="{{route('anuncios.create')}}" class="btn btn-primary">Criar novo anúncio</a><br><br>
    @endif
    <p>{{$msg}}</p>
@stop

@section('content')
@include('admin.includes.modal')

<form action="{{ route('anuncios.searchAdminAdvertisements') }}" method="POST" class="form form-inline">
    {!! csrf_field() !!}
    <input type="hidden" name="_method" value="post">
    <input type="text" name="owner_name" class="form-control" placeholder="Nome do Estabelecimento">
    <input type="text" name="descricao" class="form-control" placeholder="Descrição">
    <select name="category" id="" class="form-control">
        <option value="">Todas as categorias</option>
        @foreach ($categories as $key => $category)
            <option value="{{ $key }}">{{ $category }}</option>
        @endforeach
    </select>
    <button type="submit" class="btn btn-info"><i class="fa fa-search"></i></button>
</form><br>

<div class="box box-info">
    <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Última atualização</th>
                <th>Imagem do Anúncio</th>
                <th>Categoria do Anúncio</th>
                <th>Nome do Estabelecimento</th>
                <th>Descrição do Anúncio</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Rede Social</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($advertisements as $advertisement)
                <tr>
                    <td>{{date("d/m/Y - H:i:s", strtotime($advertisement->updated_at))}}</td>
                    <td><img style="heigth:150px; width:150px;" class="img-responsive" src="/images/advertisements-images/{{$advertisement->advertisement_images->first->image['image']}}"></td>
                    <td>{{ $advertisement->category($advertisement->category) }}</td>
                    <td>{{ $advertisement->owner_name}}</td>
                    <!-- a funcao abaixo faz um truncate da string, apresentando apenas os 50 primeiros caracteres -->
                    <td>{{ str_limit($advertisement->description, $limit = 20, $end = '...') }}</td>
                    <td>{{ $advertisement->email }}</td>
                    <td>{{ $advertisement->phone }}</td>
                    <td>{{ $advertisement->social_media }}</td>
                    <td>
                        <a href="{{route('anuncios.show', $advertisement->id)}}" class="btn btn-default">
                            <span class="fa fa-eye"></span>
                        </a>              
                    </td>
                    <td>
                        <a href="{{route('anuncios.edit', $advertisement->id)}}" class="btn btn-warning">
                            <span class="fa fa-edit"></span>
                        </a>   
                    </td>
                    <td data-form="deleteForm">
                        <form action="{{route('anuncios.destroy', $advertisement->id)}}" method="post" class="form-delete">
                            {!! csrf_field() !!}
                            <!-- necessario passar esse input pois o metodo update da controller Advertisements soh pode acessador por PUT -->
	                        <input type="hidden" name="_method" value="delete">
                            <button type="submit" value="" class="btn btn-danger"><span class="fa fa-trash"></span></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    <!-- paginacao -->
    @if (isset($dataForm))
        <!-- faz com que os parametros do filtro sejam mantidos ate quando paginar -->    
        {!! $advertisements->appends($dataForm)->links() !!}
    @else
        {!! $advertisements->links() !!}
    @endif
    </div>
</div>
@stop

<!-- script abaixo chama a modal para excluir o anuncio -->
@section('js')
    <script>
        $('td[data-form="deleteForm"]').on('click', '.form-delete', function(e){
            e.preventDefault();
            var $form = $(this);
            $('#confirm').modal({ backdrop: 'static', keyboard: false })
                .on('click', '#delete-advertisement', function(){
                    $form.submit();
                });
        });
    </script>
@stop

resources/views/admin/advertisements/show.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Exibir Anúncio')

@section('content_header')
    <h1>Exibindo Anúncio</h1>
	<a href="{{route('anuncios.index')}}" class="btn btn-default">Voltar</a>
@stop

@section('content')
<div class="box box-warning">
	<div class="box-body">
		<div class="form-group">
			<div class="row">
				<div class="col-md-4">
					<label>Imagem Principal:</label>
					<img class="img-responsive thumbnail" src="/images/advertisements-images/{{$advertisement->advertisement_images->first->image['image']}}">
				</div>
				<div class="col-md-12 row">
					@foreach($advertisement->advertisement_images as $key => $images)
						@if($key >0)
							<div class="col-md-2">
								<img class="img-responsive thumbnail" src="/images/advertisements-images/{{$images->image}}">
							</div>
						@endif
					@endforeach
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Nome do Estabelecimento:</label>
					<p>{{$advertisement->owner_name}}</p>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label>Descrição</label>
					<textarea rows="10" class="form-control" disabled> {!!$advertisement->description!!} </textarea>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Email:</label>
					<p>{{$advertisement->email}}</p>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Telefone:</label>
					<p>{{$advertisement->phone}}</p>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Rede Social:</label>
					<p>{{$advertisement->social_media}}</p>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label>Categoria:</label>
					<p> {!! $advertisement->category($advertisement->category) !!} </p>
				</div>
			</div>
		<div>
		@if($advertisement->category == 'LAN')
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Horario de Funcionamento:</label>
						<p>Abre ás: {{ date('H:i', strtotime($advertisement->open_time)) }} - Fecha ás: {{ date('H:i', strtotime($advertisement->close_time)) }}</p>
					</div>
				</div>
			<div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Delivery:</label>
						@if($advertisement->delivery == 1)
							<p>{{ $advertisement->delivery = "SIM"}}</p>
						@else
						<p>{{ $advertisement->delivery = "NÃO"}}</p>
						@endif
					</div>
				</div>
			<div>
			<br><label>Opções variadas:</label><br>
			@foreach($sandwich_variations as $key => $sandwich)
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							<input tabindex="1" type="checkbox" name="sandwich[]" id="{{$key}}" value="{{$key}}" style="margin-left:5px;" checked disabled>
							<span>{{$sandwich->sandwich_variation}}</span>
						</div>
					</div>
				<div>
			@endforeach
		@endif
		@if($advertisement->category == 'MEC')
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Horario de Funcionamento:</label>
						<p>Abre ás: {{ date('H:i', strtotime($advertisement->open_time)) }} - Fecha ás: {{ date('H:i', strtotime($advertisement->close_time)) }}</p>
					</div>
				</div>
			<div>
			<br><label>Especialidade da Mecânica:</label><br>
			@foreach($mechanic_parts as $key => $mechanic)
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							<input tabindex="1" type="checkbox" name="mechanic[]" id="{{$key}}" value="{{$key}}" style="margin-left:5px;" checked disabled>
							<span>{{$mechanic->mechanic_part}}</span>
						</div>
					</div>
				<div>
			@endforeach
		@endif
		@if($advertisement->category == 'CHA')
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Quantidade de Quartos:</label>
						<p>{{ $advertisement->room }}</p>
					</div>
				</div>
			<div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Acomodações Suportadas:</label>
						<p>{{ $advertisement->capacity }}</p>
					</div>
				</div>
			<div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Valor da diária:</label>
						<p>{{ 'R$ '.number_format($advertisement->diary_price, 2, ',', '.') }}</p>
					</div>
				</div>
			<div>
			<br><label>Áreas de Lazer:</label><br>
			@foreach($recreation_areas as $key => $recreation)
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							<input tabindex="1" type="checkbox" name="recreation[]" id="{{$key}}" value="{{$key}}" style="margin-left:5px;" checked disabled>
							<span>{{$recreation->recreation_area}}</span>
						</div>
					</div>
				<div>
			@endforeach
			<br><label>Itens Extras:</label><br>
			@foreach($extra_items as $key => $extra)
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							<input tabindex="1" type="checkbox" name="extra[]" id="{{$key}}" value="{{$key}}" style="margin-left:5px;" checked disabled>
							<span>{{$extra->extra_item}}</span>
						</div>
					</div>
				<div>
			@endforeach
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Alugada para o Feriado:</label>
						@if($advertisement->holiday == 1)
							<p>{{ $advertisement->holiday = "SIM"}}</p>
						@else
						<p>{{ $advertisement->holiday = "NÃO"}}</p>
						@endif
					</div>
				</div>
			<div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Alugada para o Natal:</label>
						@if($advertisement->christmas == 1)
							<p>{{ $advertisement->christmas = "SIM"}}</p>
						@else
						<p>{{ $advertisement->christmas = "NÃO"}}</p>
						@endif
					</div>
				</div>
			<div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-6">
						<br><label>Alugada para o Ano Novo:</label>
						@if($advertisement->new_year == 1)
							<p>{{ $advertisement->new_year = "SIM"}}</p>
						@else
						<p>{{ $advertisement->new_year = "NÃO"}}</p>
						@endif
					</div>
				</div>
			<div>
		@endif
	</div>
</div>
@stop