routes/web.php
<?php

// Route::get('/', function () {
//     return view('site.home.index');
// });

//Site
Route::get('/', 'SitesController@index');

// Buscar anúncios
Route::any('buscar-anuncios', 'SitesController@searchPublicAdvertisements')->name('anuncios.searchPublicAdvertisements');

// Promoções
Route::get('promocoes', 'SitesController@promotion')->name('promocoes.promotion');

// Sobre
Route::get('sobre', 'SitesController@about')->name('sobre.about');

// Contato
Route::get('contato', 'ContactsController@contact')->name('contato.contact');
Route::post('contato', 'ContactsController@store')->name('contato.store');

// Assinar
Route::get('assine', 'SitesController@sign')->name('assine.sign');

Route::prefix('admin')
	->middleware(['auth'])
	->group(function(){

		//acessando advertisements controller
		Route::resource('anuncios', 'AdvertisementsController');

		//acessando promotions controller
		Route::resource('promocoes', 'PromotionsController');

		// any aceita qualquer tipo de requisicao, post, get , put etc...
		Route::any('anuncios-buscar', 'AdvertisementsController@searchAdminAdvertisements')->name('anuncios.searchAdminAdvertisements');
		
		//Advertisements
		Route::post('anuncios/criar', 'AdvertisementsController@store')->name('anuncios.store');
		Route::get('meu-perfil', 'UsersController@profile')->name('profile');
		Route::post('atualizar-perfil', 'UsersController@profileUpdate')->name('profileUpdate');

		//Promotions
		Route::post('promocoes/criar', 'PromotionsController@store')->name('promocoes.store');
		Route::any('promocoes/publicar{id}', 'PromotionsController@publish')->name('promocoes.publish');
		Route::any('promocoes/despublicar{id}', 'PromotionsController@unpublish')->name('promocoes.unpublish');
	});

Auth::routes();

app/Promotion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Promotion extends Model
{
    protected $fillable = [
        'user_id', 'image', 'price', 'name', 'status', 'phone', 'owner_name'
    ];

    //promotion pertence ao user
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PromotionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PromotionUpdateFormRequest;
use App\Http\Requests\PromotionValidationFormRequest;
use Intervention\Image\Facades\Image;
use App\Promotion;
use App\User;
use File;

class PromotionsController extends Controller
{
    private $totalPages = 5;
    
    public function index(Promotion $promotions){

        $promotions = auth()->user()->promotions()->paginate($this->totalPages);
        //$promos_status = Promotion::all()->where('status', 1)->count();
        $promos_status = auth()->user()->promotions()->where('status', 1)->count();

        // tratamento para se nao houverem anuncios ainda criados
        $msg = '';
        if($promotions->isEmpty()){
            $msg = 'Não há promoções criadas';
        }
        
        return view('admin.promotions.index', compact('promotions', 'msg', 'promos_status'));
    }

    public function create(){

        return view('admin.promotions.create');
    }

    public function update(PromotionUpdateFormRequest $request, $id){

        $promotion = Promotion::findOrFail($id);

        // validando imagem e gerando novo nome
        $promo_img = $promotion->image;
        $image_name = $request->image;
        
        if($request->hasFile('image') && $request->file('image')->isValid()){
            
            //deleta a imagem da pasta public
            File::delete('images/promotions-images/'.$promo_img);
            
            $image = $request->file('image');
            $image_name = $promotion->id.$image->getClientOriginalName();
            Image::make($image)->save( public_path('/images/promotions-images/'.$image_name));
            //$request->image->storeAs('users', $image_name);
            $request->image = $image_name;
            //$request->image->save();
        }

        if($image_name == null){
            $image_name = $promotion->image;
        }

        // formata campo price para que nao de erro no banco de dados, removendo as virgulas
        $price = $request->price;
        $price_formated = floatval(preg_replace('/[^\d.]/', '', $price));

        $values = [
            'user_id' => auth()->id(), 
            'image' => $image_name,
            'price' => $price_formated,
            'name' => $request->name,
            'phone' => $request->phone,
            'owner_name' => $request->owner_name
        ];

        //atualiza requisicao
        $promotion->update($values);
        
    	//redireciona para a pagina de exibicao passando o id do anuncio em questao
    	return response()->redirectToRoute('promocoes.show', $id);
    }

    public function show($id){

        $promotion = Promotion::findOrFail($id);
        return view('admin.promotions.show', compact('promotion'));
    }

    public function edit(Promotion $promotion, $id){

        $promotion = Promotion::findOrFail($id);
        return view('admin.promotions.edit', compact('promotion'));
    }
    
    public function store(PromotionValidationFormRequest $request){
        
        // formata campo price para que nao de erro no banco de dados, removendo as virgulas
        $price = $request->price;
        $price_formated = floatval(preg_replace('/[^\d.]/', '', $price));

        // validando imagem e gerando novo nome
        $image_name = $request->image;
        if($request->hasFile('image') && $request->file('image')->isValid()){

            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            Image::make($image)->save( public_path('/images/promotions-images/'.$image_name));
            //$request->image->storeAs('users', $image_name);
            $request->image = $image_name;
            //$request->image->save();
        }

        if($image_name == null){
            $image_name = $promotion->image;
        }

        Promotion::create([
            'user_id' => auth()->id(), 
            'image' => $image_name,
            'price' => $price_formated,
            'name' => $request->name,
            'phone' => $request->phone,
            'owner_name' => $request->owner_name
        ]);

    	return response()->redirectToRoute('promocoes.index');
    }

    public function publish($id){

        $promotion = Promotion::findOrFail($id);
        $status = $promotion->status;
        if($status == 0){
            $status = 1;
        }
        $promotion->update(['status' => $status]);
        return response()->redirectToRoute('promocoes.index');
    }

    public function unpublish($id){

        $promotion = Promotion::findOrFail($id);
        $status = $promotion->status;
        if($status == 1){
            $status = 0;
        }
        $promotion->update(['status' => $status]);
        return response()->redirectToRoute('promocoes.index');
    }

    public function destroy($id){

        $promotion = Promotion::findOrFail($id);
        $promotion->delete();
        return response()->redirectToRoute('promocoes.index');
    }
}

resources/views/admin/promotions/create.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Criar Promoção')

@section('content_header')
    <h3>Criar nova promoção</h3>
	<a href="{{route('promocoes.index')}}" class="btn btn-default">Voltar</a>
@stop

@section('content')
<div class="alert alert-warning"><b>Atenção! </b>O tamanho máximo para imagens é de 3 MB.</div>
@include('admin.includes.alerts')
<!-- o enctype serve para nao falhar no post devido ao array de images -->
<form action="{{route('promocoes.store')}}" method="post" enctype="multipart/form-data">
	@include('admin.promotions.form')
</form>
@stop

resources/views/admin/promotions/edit.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Editar Promoção')

@section('content_header')
    <h1>Editar Promoção</h1>
	<a href="{{route('promocoes.index')}}" class="btn btn-default">Voltar</a><br><br>
	<div class="alert alert-warning"><b>Atenção! </b>O tamanho máximo para imagens é de 3 MB.</div>
	@include('admin.includes.alerts')
@stop

@section('content')
<form action="{{route('promocoes.update', $promotion->id)}}" method="post" enctype="multipart/form-data">
	<!-- necessario passar esse input pois o metodo update da controller Advertisements soh pode acessador por PUT -->
	<input type="hidden" name="_method" value="put">
	<!-- incluindo formulario -->
	@include('admin.promotions.form')
</form>
@stop

resources/views/admin/promotions/form.blade.php
{!! csrf_field() !!}
<div class="box box-success">
	<div class="box-body">
		<div class="form-group">
			<label for="inputImage">Imagem da Promoção</label><br>
			<input type="file" name="image" id="inputImage" class="">
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-3">
					<label for="inputOwnerName">Nome do Estabelecimento</label>
					<input type="text" class="form-control" name="owner_name" id="inputOwnerName" value="{{ $promotion->owner_name ?? ''}}">
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label for="inputName">Descrição da Promoção - Tamanho máximo de 200 caracteres <i class="fa fa-3x fa-exclamation"></i></label>
					<textarea class="form-control" name="name" id="inputName" rows="3" maxlength="200">{{ $promotion->name ?? ''}}</textarea>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-3">
					<label for="inputPhone">Telefone</label>
					<input type="text" class="form-control" name="phone" id="inputPhone" value="{{ $promotion->phone ?? ''}}">
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="inputPrice">Informe o valor da promoção</label>
			<div class="row">
				<div class="col-md-2">
					<input type="text" class="form-control" name="price" id="inputPrice" value="{{ $promotion->price ?? ''}}">
				</div>
			</div>
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-success">Salvar</button>
		</div>
	</div>
</div>

<!-- secao com chamada de jquery externo para criacao de mascaras nos inputs -->
@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>
<script>
$(document).ready(function(){
	var price = $("#inputPrice").maskMoney({symbol:'R$ ', showSymbol:true, thousands:',', decimal:'.', symbolStay: true});
	var phone = $("#inputPhone").mask("(99) 99999-9999");
});
</script>
@stop

resources/views/admin/promotions/index.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Promoções')

@section('content_header')
    <h3>Promoções</h3>
    <a href="{{route('promocoes.create')}}" class="btn btn-primary">Criar nova promoção</a><br><br>
    <p>{{$msg}}</p>
@stop

@section('content')
@include('admin.includes.modal')

<div class="box box-info">
    <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Última atualização</th>
                <th>Imagem da Promoção</th>
                <th>Nome do Estabelecimento</th>
                <th>Telefone</th>
                <th>Descrição da Promoção</th>
                <th>Valor da Promoção</th>
                <th>Visualizar</th>
                <th>Editar</th>
                <th>Excluir</th>
                <th>Ativar</th>
                <th>Desativar</th>
            </tr>
            </thead>
            <tbody>
            @foreach($promotions as $promotion)
                <tr>
                    <td>{{date("d/m/Y - H:i:s", strtotime($promotion->updated_at))}}</td>
                    <td><img style="heigth:150px; width:150px;" class="img-responsive col-md-12" src="/images/promotions-images/{{ $promotion->image }}"></td>
                    <td>{{ $promotion->owner_name}}</td>
                    <td>{{ $promotion->phone}}</td>
                    <td>{{ str_limit($promotion->name, $limit = 20, $end = '...') }}</td>
                    <td>{{ 'R$ '.number_format($promotion->price, 2, ',', '.') }}</td>
                    <td>
                        <a href="{{route('promocoes.show', $promotion->id)}}" class="btn btn-default">
                            <span class="fa fa-eye"></span>
                        </a>              
                    </td>
                    <td>
                        <a href="{{route('promocoes.edit', $promotion->id)}}" class="btn btn-warning">
                            <span class="fa fa-edit"></span>
                        </a>   
                    </td>
                    <td data-form="deleteForm">
                        <form action="{{route('promocoes.destroy', $promotion->id)}}" method="post" class="form-delete">
                            {!! csrf_field() !!}
                            <!-- necessario passar esse input pois o metodo update da controller Advertisements soh pode acessador por PUT -->
	                        <input type="hidden" name="_method" value="delete">
                            <button type="submit" value="" class="btn btn-danger"><span class="fa fa-trash"></span></button>
                        </form>
                    </td>
                    <td data-form="publishForm">
                        <form action="{{route('promocoes.publish', $promotion->id)}}" method="post" class="form-publish">
                            {!! csrf_field() !!}
                            <!-- necessario passar esse input pois o metodo update da controller Advertisements soh pode acessador por PUT -->
	                        <input type="hidden" name="_method" value="post">
                            @if($promotion->status == 0 && $promos_status == 0)
                                <button type="submit" value="" class="btn btn-success"><span class="fa fa-check-circle"></span></button>
                            @else
                                <button type="submit" value="" class="btn btn-success hidden"><span class="fa fa-check-circle"></span></button>
                            @endif
                            </label>
                        </form>
                    </td>
                    <td data-form="unpublishForm">
                        <form action="{{route('promocoes.unpublish', $promotion->id)}}" method="post" class="form-unpublish">
                            {!! csrf_field() !!}
                            <!-- necessario passar esse input pois o metodo update da controller Advertisements soh pode acessador por PUT -->
	                        <input type="hidden" name="_method" value="post">
                            @if($promotion->status == 1 && $promos_status > 0)
                                <button type="submit" value="" class="btn btn-warning"><span class="fa fa-times-circle"></span></button>
                            @else
                                <button type="submit" value="" class="btn btn-warning hidden"><span class="fa fa-times-circle"></span></button>
                            @endif
                            </label>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    <!-- paginacao -->
    {!! $promotions->links() !!}
    </div>
</div>
@stop

<!-- script abaixo chama a modal para excluir a promocao -->
@section('js')
<script>
    $('td[data-form="deleteForm"]').on('click', '.form-delete', function(e){
        e.preventDefault();
        var $form = $(this);
        $('#confirm-promotion').modal({ backdrop: 'static', keyboard: false })
            .on('click', '#delete-promotion', function(){
                $form.submit();
            });
    });
</script>

<!--Publicar-->
<script>
    $('td[data-form="publishForm"]').on('click', '.form-publish', function(e){
        e.preventDefault();
        var $form = $(this);
        $('#confirm-publish').modal({ backdrop: 'static', keyboard: false })
            .on('click', '#publish-promotion', function(){
                $form.submit();
            });
    });
</script>

<!--Despublicar-->
<script>
    $('td[data-form="unpublishForm"]').on('click', '.form-unpublish', function(e){
        e.preventDefault();
        var $form = $(this);
        $('#confirm-unpublish').modal({ backdrop: 'static', keyboard: false })
            .on('click', '#unpublish-promotion', function(){
                $form.submit();
            });
    });
</script>
@stop

resources/views/admin/promotions/show.blade.php
<!-- essa extensao abaixo eh o arquivo adminlte.php -->
@extends('adminlte::page')

@section('title', 'Exibir Promoção')

@section('content_header')
    <h1>Exibindo Promoção</h1>
	<a href="{{route('promocoes.index')}}" class="btn btn-default">Voltar</a>
@stop

@section('content')
<div class="box box-warning">
	<div class="box-body">
		<div class="form-group">
			<div class="row">
				<div class="col-md-3">
					<img class="img-responsive thumbnail" src="/images/promotions-images/{{ $promotion->image }}">
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Nome do Estabelecimento:</label>
					<p>{{ $promotion->owner_name }}</p>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label>Descrição</label>
					<textarea rows="3" class="form-control" disabled> {!!$promotion->name!!} </textarea>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Telefone:</label>
					<p>{{ $promotion->phone }}</p>
				</div>
			</div>
		<div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<br><label>Valor atual da promoção:</label>
					<p>{{ 'R$ '.number_format($promotion->price, 2, ',', '.') }}</p>
				</div>
			</div>
		<div>
	</div>
</div>
@stop